name: Shellcheck

on:
  pull_request:
    branches: [main]
    paths:
      - 'backup'
      - '.github/workflows/shellcheck.yml'

jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: shellcheck backup
